### ISSUE TITLE
Allow BSON size larger than 17 MB

### ISSUE THREAD

**Issue by jancurn** [mongodb-js/bson-ext#42]
It would be great if `MAX_BSON_SIZE` constant was replaced by the `maxBSONSize` property, so that users can generate larger BSONs than 17MB. This is related to https://github.com/mongodb/js-bson/issues/207.

I can prepare a PR if you're willing to accept it.

**Comment by mbroadst** [comment]
@jancurn that sounds reasonable, yes please create a PR

**Comment by StorytellerCZ** [comment]
@jancurn Any update on this?

**Comment by mbroadst** [comment]
@StorytellerCZ nothing has changed, this is still a requirement for the C++ version of bson. PR's are very welcome! The module now actually uses `js-bson` directly, so the approach should be to modify this code to use whatever buffer is passed in, not doing size checks in C++ at all.

**Comment by kalvinarts** [comment]
Why not do the same as [here](https://github.com/mongodb/js-bson/blob/master/lib/bson.js#L42) to set the max internal buffer size? IDK if this is posible but seems to be a good solution.

**Comment by jancurn** [comment]
Just a note that it's not easy to fork bson-ext to extend the buffer size, due to https://github.com/mongodb-js/bson-ext/issues/43

**Comment by jancurn** [comment]
Fixed in https://github.com/mongodb-js/bson-ext/pull/65
