### ISSUE TITLE
Process crashes with "terminating with uncaught exception of type char const*"

### ISSUE THREAD

**Issue by jancurn** [mongodb-js/bson-ext#43]
When using the package on Mac, sometimes my Node process crashes with `libc++abi.dylib: terminating with uncaught exception of type char const*`. These errors should not crash the process but only raise a JS exception. For example, the `BSONSerialize` method has the following code:

```cpp
try {
    // ...
} catch (char *err_msg) {
    free(final);
    Local<String> error = NanStr(err_msg);
    free(err_msg);
    return Nan::ThrowError(error);
}
```

But exception is of type `char const*`, not `char *`, so it's not caught and the process crashes.

**Comment by mbroadst** [comment]
@jancurn is it possible for you to dig a little deeper into what the actual exception is? The catch blocks here are meant to catch exceptions thrown from [ThrowAllocatedStringException](https://github.com/mongodb-js/bson-ext/blob/2.0.0/src/bson.cc#L125-L135) which does indeed throw a `char*`. I think the code should be refactored to throw `std::exception`s, but we should first identify how you are getting `const char*`

**Comment by drobnikj** [comment]
@mbroadst I got back into this issue, I was able to reproduce it. It looks the issue happens when you try to `serialize` an object larger than 16MB.
This code throws uncaught `libc++abi.dylib: terminating with uncaught exception of type char const*`
```
const BsonExt = require('bson-ext');

const BSON = new BsonExt([BsonExt.Binary, BsonExt.Code, BsonExt.DBRef, BsonExt.Decimal128, BsonExt.Double, BsonExt.Int32, BsonExt.Long, BsonExt.Map, BsonExt.MaxKey, BsonExt.MinKey, BsonExt.ObjectId, BsonExt.BSONRegExp, BsonExt.Symbol, BsonExt.Timestamp]);

const obj = {
    str: 'x'.repeat(18 * 1024 * 1024),
};

const bson = BSON.serialize(obj);
console.log(bson.byteLength);
``` 

but if you used a smaller object size it will work.
```
const BsonExt = require('bson-ext');

const BSON = new BsonExt([BsonExt.Binary, BsonExt.Code, BsonExt.DBRef, BsonExt.Decimal128, BsonExt.Double, BsonExt.Int32, BsonExt.Long, BsonExt.Map, BsonExt.MaxKey, BsonExt.MinKey, BsonExt.ObjectId, BsonExt.BSONRegExp, BsonExt.Symbol, BsonExt.Timestamp]);

const obj = {
    str: 'x'.repeat(16 * 1024 * 1024),
};

const bson = BSON.serialize(obj);
console.log(bson.byteLength);
```

**Comment by jancurn** [comment]
I found the issue and fixed it in our fork: https://github.com/apify/bson-ext/commit/559623d44eaa3a1b30320c4542338ed432bff7eb

**Comment by jancurn** [comment]
Fixed in https://github.com/mongodb-js/bson-ext/pull/65
