### ISSUE TITLE
Convert BSON to JSON string

### ISSUE THREAD

**Issue by normanrz** [mongodb-js/bson-ext#52]
I noticed that `bson-ext` doesn't yield a large performance gain compared to the JS version in my app. Since I am streaming the data from the MongoDB directly to client applications without further processing in JS, I was wondering if creating a JSON stream directly from the BSON stream would bring a larger performance benefit. This would omit the JS object creation (and GC) and create the stream directly in C++.

Let me know what you think and if you'd be interested in such a contribution.

**Comment by mbroadst** [comment]
@normanrz the perf benefits claimed by this module were last tested in very early versions of node. I'm not sure the gap is so wide anymore. Can you better describe your application, and why you think the JSON stream would be more performant? The stream would still require creation of objects.

**Comment by normanrz** [comment]
I have an api server that essentially forwards the result of a mongo aggregation as json to the client. In a particular case that result contains a document array of ~20k objects (plus subobjects). Constructing and GC-ing that many objects can be quite an overhead. Since, I am not doing anything with these objects except for JSON-serializing them, I was wondering if the C++ extension could do this conversion directly. Of course there would be some objects that are created, but it would be less by an order of magnitude at least.

**Comment by marcj** [comment]
That's a wonderful idea. I have the exact same feature request :) I read many megabytes of documents out of the db without doing anything but sending as json to the client. Currently it processes BSON -> JS objects -> JSON, where the JS objects are not at all necessary. I imagine I can safe tons of cpu time that way. Actually, I don't even need that to be converted to JSON, I could send it as BSON to the client to gain even faster response times. The client can easily unserialize it from BSON to JS objects using the `js-bson` package. Is it currently possible to fetch from the driver the raw BSON and disable all unserialization?

**Comment by zbjornson** [comment]
>  Is it currently possible to fetch from the driver the raw BSON and disable all unserialization?

@marcj yes, using the `raw: true` option (see docs for e.g. [`find`](https://mongodb.github.io/node-mongodb-native/3.3/api/Collection.html#find)). In one benchmark I ran (2600-element array of medium-sized objects, sent as BSON and decoded on the client), that saved ~40ms of BSON deserialization and ~30ms of JSON serialization server-side, but replaced ~9ms of JSON deserialization with ~40ms of BSON deserialization client-side. The BSON response (with DEFLATE) was also slightly larger.

It'd be very interesting to know if transcoding a BSON directly to a JSON string (per OP) would be faster.

**Comment by zbjornson** [comment]
It turns out the answer is a definite *yes*. I made a module that converts BSON directly to JSON here:

https://github.com/zbjornson/bson-to-json

It's about 22x faster than `JSON.stringify(BSON.deserialize(arr))`.

**Comment by marcj** [comment]
@zbjornson that's wonderful, thanks for all the work!

> ~40ms of BSON deserialization client-side
I guess

**Comment by zbjornson** [comment]
No prob :).

I haven't tried compiling to webassembly. Every time I want to do some heavy work on binary data with webassembly, I'm sadly reminded that memory has to be copied in and out, which for everything I've tried so far has negated the performance gains of using wasm.

**Comment by mbroadst** [comment]
@zbjornson very cool! I have a prototype laying around somewhere of a Rust project that reads raw BSON bytes and returns an `eval`able string for serialization. Returning raw JSON would be feasible, and potentially very fast

**Comment by mbroadst** [comment]
BTW, I've created https://jira.mongodb.org/browse/NODE-2436 to track support for this in our BSON module. We're unfortunately a bit short staffed at the moment, and focusing on 4.4 work, but this seems like something we'd like to prioritize in the upcoming months.

**Comment by bajanam** [comment]
This issue is being tracked in Jira, please continue all conversations in the corresponding Jira ticket. Thanks!
