### ISSUE TITLE
TypeError: First argument passed in must be an array of types

### ISSUE THREAD

**Issue by adityapatadia** [mongodb-js/bson-ext#53]
This is error thrown by bson-ext when `useUnifiedTopology: true` is done for mongodb driver version 3.3.

Please also check this issue: https://jira.mongodb.org/browse/NODE-2092

**Comment by mbroadst** [comment]
Hi @adityapatadia, this should be resolved in v3.3.3 of the driver. It has a fix tracked [here|https://jira.mongodb.org/browse/NODE-2092].
