### ISSUE TITLE
Topology error in Node v12

### ISSUE THREAD

**Issue by orbitlens** [mongodb-js/bson-ext#54]
I noticed that you added support for Node 10&12 recently. Thanks @normanrz and @mbroadst for looking into this. Appreciate the effort. 

However, when I tried to use the latest v2.0.3 version, I faced the following error:

```
TypeError: First argument passed in must be an array of types
    at new Topology (/app/node_modules/mongodb/lib/core/sdam/topology.js:136:29)
    at new NativeTopology (/app/node_modules/mongodb/lib/topologies/native_topology.js:36:5)
    at createTopology (/app/node_modules/mongodb/lib/operations/connect.js:454:16)
    at /app/node_modules/mongodb/lib/operations/connect.js:309:14
    at parseConnectionString (/app/node_modules/mongodb/lib/core/uri_parser.js:628:3)
    at connect (/app/node_modules/mongodb/lib/operations/connect.js:266:3)
    at ConnectOperation.execute (/app/node_modules/mongodb/lib/operations/connect.js:191:5)
    at /app/node_modules/mongodb/lib/operations/execute_operation.js:98:26
    at new Promise (<anonymous>)
    at executeOperation (/app/node_modules/mongodb/lib/operations/execute_operation.js:91:10)
```

Connection settings: 
```js
{
    appname: 'app',
    replicaSet: 'default'
    useNewUrlParser: true,
    keepAlive: true,
    reconnectTries: 10000,
    useUnifiedTopology: true,
    promoteValues: true,
    promoteLongs: false,
    authSource: 'admin'
    reconnectInterval: 1000,
    poolSize: 20
}
```

**Environment**: Node 12.2.0, Centos 7.6, replica set with a single server in it.

Please let me know what extra info I can provide to simplify this bug troubleshooting.

Again, thanks for taking time to fix this long-awaited functionality.

**Comment by mbroadst** [comment]
Hi @orbitlens! Sorry for the late response here, but version 3.3.3 of the driver was just released this morning and it includes a fix tracked [here|https://jira.mongodb.org/browse/NODE-2092]. Can you please try that version and let us know if you still experience this issue?

**Comment by orbitlens** [comment]
Hey @mbroadst,
Yes, new release fixed the problem, thanks. 

However, after running a few generic tests, I got inferior serialization performance comparing to the vanilla `bson` package. 
- JS `Number` serialization is about 30% slower
- `BSON.Int32` serialization is ~2x slower
- `BSON.Int64` serialization is ~4x slower
- `String` serialization shows roughly the same performance

The results look disappointing, so I'm going to dig deeper into the plain `bson` package and try to squeeze a few more bits of performance from it. Maybe `worker threads` will allow to serialize a multiple mongodb commands in parallel.

Anyways, thanks for looking into this.

**Comment by mbroadst** [comment]
@orbitlens this module was written years ago, it would not surprise me that V8 has caught up in performance in the meantime. We don't actively work on this module either, so it's possible that there are ways to improve performance here as well.
