### ISSUE TITLE
Cannot compile on ARM platform

### ISSUE THREAD

**Issue by haakonnessjoen** [mongodb-js/bson-ext#55]
Cant compile on Raspbery PI because of the "-msse2" flag. Since SSE2 does not exist on the ARM architecture.

**Comment by daprahamian** [comment]
Filed https://jira.mongodb.org/browse/NODE-2239 to track

**Comment by bajanam** [comment]
This issue is being tracked in Jira, please continue all conversations in the corresponding Jira ticket. Thanks!
